# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('kA', models.FloatField(blank=True, default=0, verbose_name='Team A Coefficient')),
                ('kB', models.FloatField(blank=True, default=0, verbose_name='Team B Coefficient')),
                ('catChoice', models.CharField(blank=True, choices=[('', ''), ('A', 'Team A'), ('B', 'Team B')], max_length=255, verbose_name='Cat choice')),
                ('scoreA', models.IntegerField(blank=True, default=0, verbose_name='Score A')),
                ('scoreB', models.IntegerField(blank=True, default=0, verbose_name='Score B')),
                ('betSum', models.IntegerField(blank=True, default=0, verbose_name='Bet summ')),
                ('link', models.URLField(blank=True, default='', verbose_name='Bet link')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='teamA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='kittySite.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='teamB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='kittySite.Team'),
        ),
    ]
